---
title: "Final"
author: "Harley Combest"
date: "`r Sys.Date()`"
output:
  html_document:
      toc: yes
      toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tasks

```{r}
alpha=.02
set.seed(0)
x=rnorm(25, mean=5, sd = 5)
t.test(x=x, mu = 5)
7.113861-5.19959
qt(c((1-alpha)/2, alpha/2),df =25-1)
```

```{r}
invquad=read.csv("INVQUAD-1.csv")
electric=invquad[invquad$PLANT=="Electric",]
gas=invquad[invquad$PLANT=="Gas",]


var(electric$INV.QUAD)/var(gas$INV.QUAD)

var.test(electric$INV.QUAD, gas$INV.QUAD)

t.test( electric$INV.QUAD, gas$INV.QUAD, var.equal = TRUE)
```

```{r}
kwhrs=read.csv("KWHRS-1.csv")

kwhrsLm=lm(kwhrs)
kwhrsLm


library(s20x)

ciReg(kwhrsLm, conf.level = .95, print.out = TRUE)

anova(kwhrsLm)
```

```{r}
(7925249 + 100997 + 611 )/(7925249 + 100997 + 7327)
```
```{r}
(1.291e+03)/(1.175e+02)
```

```{r}
 (4.506e-02) * (4.904)
```

```{r}
(2^2)*(19)+(3^2)*(16)+((-1)^2)*(16)
```

```{r}
pexp(q = 4, rate = 3)
pgamma(14,shape = 2,rate=4)- pgamma(9,shape=2, rate=4)
```

```{r}
.01196426061 + .00115947187*10.31872
.01196426061 - .00115947187*10.31872

```

