---
title: "task7"
author: "Harley Combest"
date: "`r Sys.Date()`"
output: 
    html_document:
      toc: yes
      toc_float: yes
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r slr, echo=FALSE}
library(ggplot2)
# DATA
spruce.df = read.csv("SPRUCE.csv")#MS pg478

library(shiny)
# INPUTS
inputPanel(
  
  
  selectInput("plotg", "Choose plot type",
      list(
        `choices` = c("Straight Simple Linear Regression Line", "Points Alone", "Points Jointed and Line Segmented")
      )
    )
)

renderPlot({
  
 pointsAlone = ggplot(spruce.df, aes(x = BHDiameter, y = Height)) + geom_point() 

 pointsJointSegment = pointsAlone + geom_line()
 
 sslrl = pointsAlone + geom_smooth(method="lm")
  
 if(input$plotg == "Points Alone") print(pointsAlone)
 
 if(input$plotg == "Points Jointed and Line Segmented")   print(pointsJointSegment)
 
 if(input$plotg == "Straight Simple Linear Regression Line")   print(sslrl)
 
 
   
})
```
